spring:
  redis:
    host: 47.109.33.195
    port: 6379
    password: 123123
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
