spring:
  datasource:
    url: jdbc:mysql://47.109.33.195:3307/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.109.33.195
    port: 6379
    password: 123123
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl